### PR TITLE
Splitting the application up into several form fields instead of having it in one big text box

### PR DESCRIPTION
**Pull request by arelenglish**
TODO: 

Form validation

add the fields together into one DB field and put line breaks between each question

### CODE REVIEW

**Comment by arelenglish** [comment]
This deals with  issue #16

**Comment by tjlahr** [comment]
@arelenglish, I'm happy to take care of those todos. Can you grant me push access to your fork? I'll add them there and then update the pull request.

**Comment by arelenglish** [comment]
Yep, you should have push access now.

**Comment by tjlahr** [comment]
update: I've got the field concatenation and the client-side validation working on arel's fork, but the POST doesn't seem to work. The POST to /apply/accounts returns 200, so the request is going through, but the page doesn't redirect. I'll dig into this when I get more time, but I'm not familiar with the backend yet so it could take a while to debug.

There's also weirdness with the fact that some fields are validated on the client and some on the server. I'm assuming we're going to replace all of that anyway, so I'm going to leave that as is until we fix with a more general JS approach.

**Pull request closed without merging**
